### ISSUE TITLE
Support for OSM descriptors

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-descriptorgen#11]
Support generating OSM descriptors

**Comment by stefanbschneider** [comment]
I'm currently creating default descriptors [here](https://github.com/sonata-nfv/tng-sdk-descriptorgen/tree/master/osm).

It seems like one of the bigger differences between OSM and Tango are the connection points. 5GTANGO's network services have connection points mgmt, input, output for access from the outside:

```
connection_points:
  - id: "mgmt"
    interface: "ipv4"
    type: "management"
  - id: "input"
    interface: "ipv4"
    type: "external"
  - id: "output"
    interface: "ipv4"
type: "external"

```
Whereas OSM just connects the VNFs but does not consider input/output from the outside. See: https://osm.etsi.org/wikipub/index.php/Reference_VNF_and_NS_Descriptors_(Release_THREE)
--> Just drop input/output connection points when creating NSDs for OSM.

Also OSM just uses IDs to indentify NSDs and VNFDs, rather than vendor:name:version like in Tango
